### PR TITLE
Respect SupportedOSPlatformAttribute on exports.

### LINKED ISSUE #82: Request: Honor `SupportedOSPlatformAttribute` when emitting `.g.c` file.
Would be nice if this would work...

```csharp
    public static Exports
    {
        [SupportedOSPlatform("windows")]
        [UnmanagedCallersOnly(EntryPoint = "GetPluginFactory")]
        public static IntPtr GetPluginFactory_Win()
        {  ...  }

        [SupportedOSPlatform("linux")]
        [UnmanagedCallersOnly(EntryPoint = "GetPluginFactory")]
        public static IntPtr GetPluginFactory_Lnx()
        {  ...  }
```

Currently (v1.0.23) there is an (C/C++) compiler error that indicates both variations are being emitted in the generated .c file.
Windows `error C2084: function 'intptr_t GetPluginFactory(void)' already has a body`
Linux `error G94CD4D9A: redefinition of 'GetPluginFactory'`

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Add tests for all currently defined .NET platforms.

Fixes #82

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Could you do me a favor and give this a quick pass? I don't see any need for `UnsupportedOSPlatformAttribute` for native exporting but could be missing something.

**Comment by jkoritzinsky** [comment]
This generally looks good. I think implementing the whole spec for these attribute types would be useful, primarily for cases that might use some sort of underlying APIs that only work on some platforms (or to enable the `UnmanagedCallersOnly` method to use methods with `UnsupportedOSPlatformAttribute` in managed code and have that reflected properly in the native exports without causing analyzer diagnostics).

I'd suggest doing `#ifndef` for the "unsupported OS" cases, which should be pretty simple.

**Comment by AaronRobinsonMSFT** [comment]
> I'd suggest doing #ifndef for the "unsupported OS" cases, which should be pretty simple.

Sigh... fine :-) It is simple for sure.

**Comment by AaronRobinsonMSFT** [comment]
> I think implementing the whole spec for these attribute types would be useful

Ugh. This is more complicated since multiple are allowed.... boo.

**Pull request merged**
